# Generated by Django 4.2.5 on 2023-11-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='confirm_password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userotp',
            field=models.IntegerField(null=True),
        ),
    ]
