# Generated by Django 4.2.5 on 2023-11-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_name_customuser_confirm_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customuser',
        ),
    ]
