# Generated by Django 4.2.5 on 2023-11-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CaptchaModel',
        ),
    ]
