# Generated by Django 4.2.5 on 2023-12-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_sendemail_delete_captchamodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendEmail',
        ),
    ]
