# Generated by Django 4.2.5 on 2023-12-16 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_alter_studentsocialmedia_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='notification_img')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('pen', models.BooleanField(blank=True, default=False, null=True)),
                ('creted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
