# Generated by Django 4.2.5 on 2023-12-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_studentstories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstories',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
