# Generated by Django 4.2.5 on 2023-12-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_studentstories_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstories',
            name='pen',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
