# Generated by Django 4.2.5 on 2023-12-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_studentstories_pen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstories',
            old_name='student',
            new_name='student_story',
        ),
    ]
