# Generated by Django 4.2.5 on 2023-12-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_studentstories_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstories',
            name='student_story',
        ),
        migrations.AddField(
            model_name='studentstories',
            name='student',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
