# Generated by Django 4.2.5 on 2023-12-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_studentstories_student_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstories',
            name='pen',
            field=models.BooleanField(default=False),
        ),
    ]
