# Generated by Django 4.2.5 on 2023-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_studentstories_pen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstories',
            name='pen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
